version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: aavhan_postgres
    restart: always
    environment:
      POSTGRES_USER: aavhan_user
      POSTGRES_PASSWORD: aavhan_password
      POSTGRES_DB: aavhan_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: